#!/bin/bash

ROUTE="auth/signin"
METHOD="POST"
DATA=$(
	jq -n \
		--arg email "$1" \
		--arg password "$2" \
		'{
		email: $email,
		password: $password
	}'
)

source "$(dirname "${BASH_SOURCE[0]}")/../request"
