#!/bin/bash

ROUTE="events/"
METHOD="POST"
DATA=$(
	jq -n \
		--arg name "$1" \
		--arg description "$2" \
		--arg address "$3" \
		--arg start_time "$4" \
		--arg end_time "$5" \
		'{
	name: $name,
	description: $description,
	address: $address,
	start_time: $start_time,
	end_time: $end_time
}'
)

source "$(dirname "${BASH_SOURCE[0]}")/../request"
